# SPDX-License-Identifier: GPL-2.0-or-later
"""Reference dataset RD-04: levelling with a known truth (specs/20 section 3).

**What this is, stated plainly**, as for RD-02 and RD-03 before it: not a
transcription from Ghilani or Gemael. Those books are not available to the
author of this module and inventing a citation would be worse than having none.
RD-04 is a set of levelling field books **generated from known heights**, so the
answer is known exactly rather than to the precision a book happened to print.

That is a real standard and in one respect a stronger one. A published worked
example is checked by comparing two numbers; these are generated by inverting
the very equations under test, from a truth chosen in advance, with the noise
drawn from a fixed seed (NFR-007). A sign error in the collimation correction
does not merely produce a different number here -- it produces a line that fails
to recover a height it must recover exactly, in the noiseless case, which is the
strongest form of the check available without the books.

**How a reading is generated.** An instrument's horizontal line of sight sits at
some height *Z*. A staff on a station of height *H* at distance *d* reads::

    r = Z - H + c * d + noise

with *c* the collimation. Every reading in this module comes from that one line,
so a test that recovers *H* has verified the whole chain -- reading, setup, line,
collimation, closure and network -- against the geometry it came from.

Transcribing the published worked examples remains outstanding and is recorded
in ``specs/20-testing-and-validation.md``.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from geocomp.core.instruments.level import LevellingClass, LevelProfile
from geocomp.core.techniques.levelling.line import LevellingLine
from geocomp.core.techniques.levelling.readings import LevelSetup, StaffReading
from geocomp.core.techniques.levelling.schemes import ReciprocalPair
from geocomp.core.uncertainty import Quantity
from geocomp.core.units import Unit

METRE = Unit.METRE

#: Fixed so every reference book is reproducible (NFR-007).
SEED = 20260828

#: One staff reading's standard deviation, metres. A precise level with an
#: invar staff; the figure is the dataset's own definition, not a claim about
#: any real instrument.
SIGMA_READING = 0.0005

#: The sight distance's standard deviation, metres. Loose on purpose: a sight
#: distance is paced or read by stadia and never matters to a millimetre.
SIGMA_DISTANCE = 0.5

#: The truth. Heights in metres, chosen to span a range large enough that a
#: sign error in any Delta h is unmistakable.
HEIGHTS: dict[str, float] = {
    "BM1": 100.000,
    "BM2": 103.750,
    "BM3": 101.200,
    "BM4": 106.480,
    "S1": 102.310,
    "S2": 104.905,
}


def profile(
    *,
    collimation: float = 0.0,
    collimation_sigma: float = 0.0,
    applies_collimation: bool = False,
) -> LevelProfile:
    """The RD-04 instrument, with the collimation the case under test needs."""
    return LevelProfile(
        id="rd04-level",
        name="RD-04 reference level",
        collimation=(
            Quantity.exact(collimation, Unit.RADIAN)
            if collimation_sigma == 0.0
            else Quantity.from_std_dev(collimation, collimation_sigma, Unit.RADIAN)
        ),
        applies_collimation=applies_collimation,
        sigma_per_km=0.0007,
        sigma_per_setup=0.0003,
        sigma_reading=SIGMA_READING,
        stadia_factor=100.0,
    )


def levelling_class(*, coefficient: float = 0.008) -> LevellingClass:
    """A second-order-like class. **The coefficient is this dataset's own.**

    GeoComp ships no national tolerance table and RD-04 does not smuggle one in:
    ``0.008 m per root kilometre`` is a plausible value chosen so the passing and
    failing cases below are unambiguous, and it is cited to nothing.
    """
    return LevellingClass(
        id="rd04",
        name="RD-04 reference class",
        tolerance_coefficient=coefficient,
        max_sight_length=60.0,
        max_sight_imbalance=2.0,
        max_accumulated_imbalance=5.0,
        source="RD-04 itself; see the docstring. Not from any standard.",
    )


@dataclass
class ReferenceBook:
    """A generated field book, and the truth it was generated from."""

    line: LevellingLine
    truth: dict[str, float] = field(default_factory=lambda: dict(HEIGHTS))
    collimation: float = 0.0
    noise: float = 0.0

    @property
    def true_difference(self) -> float:
        """The height difference the line must recover."""
        return self.truth[self.line.to_station] - self.truth[self.line.from_station]

    def true_difference_between(self, first: str, second: str) -> float:
        return self.truth[second] - self.truth[first]


def _reading(
    station: str,
    sight_height: float,
    distance: float,
    *,
    collimation: float,
    heights: dict[str, float],
    rng: np.random.Generator | None,
    noise: float,
    sigma: float = SIGMA_READING,
) -> StaffReading:
    """One staff reading, generated from the truth by ``r = Z - H + c*d``."""
    value = sight_height - heights[station] + collimation * distance
    if rng is not None and noise > 0.0:
        value += float(rng.normal(0.0, noise))
    return StaffReading(
        station=station,
        reading=Quantity.from_std_dev(value, sigma, METRE),
        distance=Quantity.from_std_dev(distance, SIGMA_DISTANCE, METRE),
    )


def _setup(
    setup_id: str,
    backsight: str,
    foresights: tuple[str, ...],
    *,
    back_distance: float,
    fore_distances: tuple[float, ...],
    sight_height: float,
    collimation: float,
    heights: dict[str, float],
    rng: np.random.Generator | None,
    noise: float,
) -> LevelSetup:
    return LevelSetup(
        id=setup_id,
        backsight=_reading(
            backsight,
            sight_height,
            back_distance,
            collimation=collimation,
            heights=heights,
            rng=rng,
            noise=noise,
        ),
        foresights=tuple(
            _reading(
                station,
                sight_height,
                distance,
                collimation=collimation,
                heights=heights,
                rng=rng,
                noise=noise,
            )
            for station, distance in zip(foresights, fore_distances, strict=True)
        ),
    )


def balanced_line(
    *,
    collimation: float = 0.0,
    noise: float = 0.0,
    seed: int = SEED,
    line_id: str = "RD04-balanced",
) -> ReferenceBook:
    """BM1 to BM2 in three setups, every setup exactly balanced (FR-500).

    The case that proves the preferred method: with equal sights the collimation
    cancels **whatever its value**, so the line recovers the truth exactly even
    when the instrument is badly out of adjustment.
    """
    rng = np.random.default_rng(seed) if noise else None
    heights = dict(HEIGHTS)
    plan = (
        ("BM1", "T1", 30.0, 30.0, 101.700),
        ("T1", "T2", 28.0, 28.0, 102.900),
        ("T2", "BM2", 32.0, 32.0, 104.400),
    )
    heights["T1"], heights["T2"] = 101.100, 102.200

    setups = tuple(
        _setup(
            f"S{index + 1}",
            back,
            (fore,),
            back_distance=back_d,
            fore_distances=(fore_d,),
            sight_height=sight_height,
            collimation=collimation,
            heights=heights,
            rng=rng,
            noise=noise,
        )
        for index, (back, fore, back_d, fore_d, sight_height) in enumerate(plan)
    )
    return ReferenceBook(
        line=LevellingLine(id=line_id, setups=setups),
        truth=heights,
        collimation=collimation,
        noise=noise,
    )


def imbalanced_line(
    *,
    collimation: float = 2.0e-4,
    noise: float = 0.0,
    seed: int = SEED,
    line_id: str = "RD04-imbalanced",
) -> ReferenceBook:
    """The same route, every setup out of balance by +20 m (FR-500).

    Three setups, each with a 40 m backsight and a 20 m foresight, so the
    imbalance accumulates to 60 m instead of cancelling. With a collimation of
    2e-4 rad the raw line is wrong by ``-c * 60 = -12 mm`` -- large, systematic,
    and invisible without the distances. Correcting it recovers the truth
    exactly.
    """
    rng = np.random.default_rng(seed) if noise else None
    heights = dict(HEIGHTS)
    heights["T1"], heights["T2"] = 101.100, 102.200
    plan = (
        ("BM1", "T1", 40.0, 20.0, 101.700),
        ("T1", "T2", 40.0, 20.0, 102.900),
        ("T2", "BM2", 40.0, 20.0, 104.400),
    )

    setups = tuple(
        _setup(
            f"S{index + 1}",
            back,
            (fore,),
            back_distance=back_d,
            fore_distances=(fore_d,),
            sight_height=sight_height,
            collimation=collimation,
            heights=heights,
            rng=rng,
            noise=noise,
        )
        for index, (back, fore, back_d, fore_d, sight_height) in enumerate(plan)
    )
    return ReferenceBook(
        line=LevellingLine(id=line_id, setups=setups),
        truth=heights,
        collimation=collimation,
        noise=noise,
    )


def extreme_sights_setup(
    *, noise: float = 0.0, seed: int = SEED, setup_id: str = "RD04-extreme"
) -> tuple[LevelSetup, dict[str, float]]:
    """One setup, one backsight on BM1 and three foresights (FR-502).

    The configuration the correlation criterion is about: BM3, S1 and S2 are all
    levelled from one instrument position, so every difference between two of
    them is free of the backsight's error entirely.
    """
    rng = np.random.default_rng(seed) if noise else None
    setup = _setup(
        setup_id,
        "BM1",
        ("BM3", "S1", "S2"),
        back_distance=25.0,
        fore_distances=(25.0, 40.0, 18.0),
        sight_height=107.000,
        collimation=0.0,
        heights=HEIGHTS,
        rng=rng,
        noise=noise,
    )
    return setup, dict(HEIGHTS)


def reciprocal_crossing(
    *,
    refraction: float = 0.012,
    noise: float = 0.0,
    seed: int = SEED,
) -> tuple[ReciprocalPair, ReciprocalPair, float]:
    """BM1 to BM2 across a river, observed from both banks (FR-501).

    The far sight of each pair carries ``refraction`` metres of systematic
    error, entering the two determinations with opposite sign. It must cancel in
    the mean **exactly**, and the two determinations must disagree by twice it,
    which is what the discrepancy check is for.

    Returns the two pairs and the true height difference.
    """
    rng = np.random.default_rng(seed) if noise else None

    def read(station: str, sight_height: float, distance: float, bias: float) -> StaffReading:
        reading = _reading(
            station,
            sight_height,
            distance,
            collimation=0.0,
            heights=HEIGHTS,
            rng=rng,
            noise=noise,
        )
        return StaffReading(
            station=station,
            reading=Quantity.from_std_dev(reading.reading.value + bias, SIGMA_READING, METRE),
            distance=reading.distance,
        )

    near_bank = ReciprocalPair(
        setup_id="RD04-bankA",
        near=read("BM1", 101.500, 8.0, 0.0),
        far=read("BM2", 101.500, 220.0, refraction),
    )
    far_bank = ReciprocalPair(
        setup_id="RD04-bankB",
        near=read("BM2", 105.200, 8.0, 0.0),
        far=read("BM1", 105.200, 220.0, refraction),
    )
    return near_bank, far_bank, HEIGHTS["BM2"] - HEIGHTS["BM1"]


def loop(
    *,
    noise: float = 0.0004,
    seed: int = SEED,
    blunder: float = 0.0,
    blunder_on: str = "",
) -> tuple[list[ReferenceBook], dict[str, float]]:
    """A three-line loop BM1 -> BM2 -> BM4 -> BM1, with varying sight lengths.

    Sight lengths differ between the lines **on purpose**: with a constant sight
    length the length- and setup-weighting models are proportional to each other
    and give identical results, which would make a test comparing them prove
    nothing. Here they differ, so the comparison has content.

    Args:
        blunder: Metres to add to one line's last foresight reading, which is
            how a real blunder enters -- one reading, not a whole line.
        blunder_on: Which line to injure. Empty injures none.
    """
    rng = np.random.default_rng(seed)
    heights = dict(HEIGHTS)
    books: list[ReferenceBook] = []

    plan = {
        "BM1-BM2": ("BM1", "BM2", 3, 30.0),
        "BM2-BM4": ("BM2", "BM4", 5, 50.0),
        "BM4-BM1": ("BM4", "BM1", 2, 20.0),
    }

    for line_id, (start, end, count, sight) in plan.items():
        span = heights[end] - heights[start]
        setups = []
        previous = start
        for index in range(count):
            station = end if index == count - 1 else f"{line_id}-T{index}"
            if station not in heights:
                heights[station] = heights[start] + span * (index + 1) / count
            sight_height = max(heights[previous], heights[station]) + 1.500
            setups.append(
                _setup(
                    f"{line_id}-S{index}",
                    previous,
                    (station,),
                    back_distance=sight,
                    fore_distances=(sight,),
                    sight_height=sight_height,
                    collimation=0.0,
                    heights=heights,
                    rng=rng,
                    noise=noise,
                )
            )
            previous = station

        if blunder and line_id == blunder_on:
            last = setups[-1]
            injured = last.foresights[0]
            setups[-1] = LevelSetup(
                id=last.id,
                backsight=last.backsight,
                foresights=(
                    StaffReading(
                        station=injured.station,
                        reading=Quantity.from_std_dev(
                            injured.reading.value + blunder, SIGMA_READING, METRE
                        ),
                        distance=injured.distance,
                    ),
                ),
            )

        books.append(
            ReferenceBook(
                line=LevellingLine(id=line_id, setups=tuple(setups)),
                truth=heights,
                noise=noise,
            )
        )

    return books, heights
