# SPDX-License-Identifier: GPL-2.0-or-later
"""Gravimetric networks, judged on ``specs/12`` section 8.

The surveys are USGS's synthetic test cases for GSadjust, vendored verbatim in
``tests/data/rd07/gsadjust/`` (public domain; ``PROVENANCE.md`` there). Their
value is that the truth is *known and published beside the data*: five stations
at 50, 48, 45, 48.5 and 46 mGal, a stated drift, stated calibration factors and
readings with a stated 3 microgal noise -- generated by somebody else, so a
result that recovers them is not recovering its own assumptions.

The truth is transcribed below rather than read from the workbook at every run,
so these tests need nothing beyond NumPy; one test checks the transcription
against the workbook wherever openpyxl is installed.

The published *solution* half of RD-07 -- pyGrav's -- cannot be vendored and is
checked by ``scripts/check_rd07.py`` in the ``reference`` workflow.
"""

from __future__ import annotations

import math
from datetime import UTC, datetime, timedelta
from itertools import pairwise
from pathlib import Path

import pytest

from geocomp.core.instruments import GravimeterProfile, ProfileLibrary
from geocomp.core.models import ConstraintMode, ConstraintSpec, Station
from geocomp.core.techniques.gravimetry import (
    AbsoluteGravity,
    DriftMode,
    DriftOptions,
    DriftTreatment,
    GravityReading,
    adjust_gravity_network,
    build_gravity_network,
    compare_treatments,
    drift_is_estimable,
    group_occupations,
    reduce_readings,
)
from geocomp.core.uncertainty import Quantity, Strategy, UncertaintyMode
from geocomp.core.units import METRES_PER_SECOND_SQUARED_PER_MGAL as MGAL
from geocomp.core.units import METRES_PER_SECOND_SQUARED_PER_UGAL as UGAL
from geocomp.core.units import Unit

DATA = Path(__file__).parent / "data" / "rd07" / "gsadjust"

#: GSadjust_TestData.xlsx, the "True" data table of every sheet, mGal.
TRUTH = {"sta1": 50.0, "sta2": 48.0, "sta3": 45.0, "sta4": 48.5, "sta5": 46.0}
#: Each sheet's stated drift (mGal/h) and calibration per meter. The readings
#: are the calibration times the truth, so the factor that recovers the truth
#: is its reciprocal. Test 5's drift is a piecewise function, not a rate.
CASES = {
    "Test1": {"drift_mgal_h": 0.0, "calibration": {"B44": 1.0}},
    "Test2": {"drift_mgal_h": 0.01, "calibration": {"B44": 1.0}},
    "Test3": {"drift_mgal_h": 0.01, "calibration": {"B44": 1.03}},
    "Test4": {"drift_mgal_h": 0.01, "calibration": {"B44": 1.1, "B108": 1.05}},
    "Test5": {"drift_mgal_h": None, "calibration": {"B44": 1.003}},
}
#: "Station standard deviation, mGal" on every sheet.
SIGMA_MGAL = 0.003


def _readings(case: str, *, extra: list[tuple[str, str]] | None = None) -> list[GravityReading]:
    """Parse a Burris-format test file. Times are UTC; the tide column is zero,
    so the readings are declared tide-corrected rather than corrected again."""
    readings = []
    for number, line in enumerate((DATA / f"{case}.txt").read_text().splitlines()):
        fields = line.split()
        if len(fields) < 16:
            continue
        instant = datetime.strptime(f"{fields[3]} {fields[4]}", "%Y/%m/%d %H:%M:%S").replace(tzinfo=UTC)
        readings.append(
            GravityReading(
                id=f"{case}:{number}",
                station=fields[0],
                instant=instant,
                value=Quantity.from_std_dev(float(fields[5]) * MGAL, SIGMA_MGAL * MGAL, Unit.ACCELERATION),
                instrument=fields[2],
                session=f"{fields[2]} {fields[3]}",
                latitude=math.radians(float(fields[14])),
                longitude=math.radians(float(fields[15])),
                height=float(fields[13]),
                tide_applied=True,
            )
        )
    for station, reading in extra or ():
        last = readings[-1]
        readings.append(
            GravityReading(
                id=f"{case}:extra:{station}",
                station=station,
                instant=last.instant + timedelta(minutes=20),
                value=Quantity.from_std_dev(float(reading) * MGAL, SIGMA_MGAL * MGAL, Unit.ACCELERATION),
                instrument=last.instrument,
                session=last.session,
                latitude=last.latitude,
                longitude=last.longitude,
                tide_applied=True,
            )
        )
    return readings


def _library(case: str) -> ProfileLibrary:
    library = ProfileLibrary()
    for meter, calibration in CASES[case]["calibration"].items():
        library.add_gravimeter(
            GravimeterProfile(id=meter, calibration_factor=Quantity.exact(1.0 / calibration))
        )
    return library


def _held_at_truth(built, station: str = "sta1") -> None:
    held = built.network.stations[station]
    built.network.stations[station] = Station(
        id=station,
        approx_position=held.approx_position,
        constraint=ConstraintSpec(
            mode=ConstraintMode.FIXED,
            components=frozenset({"gravity"}),
            gravity=Quantity.exact(TRUTH[station] * MGAL, Unit.ACCELERATION),
        ),
    )


def _survey(case: str, *, fixed: bool = True, absolutes=(), extra=None, **drift):
    library = _library(case)
    built = build_gravity_network(
        reduce_readings(_readings(case, extra=extra), library),
        library,
        absolutes=list(absolutes),
        drift=DriftOptions(**drift),
    )
    if fixed:
        _held_at_truth(built)
    return adjust_gravity_network(built)


def _errors(result) -> dict[str, tuple[float, float]]:
    """Each estimated station's error against the truth, and its sigma, in mGal."""
    return {
        s: ((result.gravity(s).value / MGAL) - TRUTH[s], result.gravity(s).std_dev / MGAL)
        for s in TRUTH
        if result.run.layout.column(s, "g") is not None
    }


class TestTheTruthIsRecovered:
    """Criterion 2, and the scale correction as a working part of it."""

    @pytest.mark.parametrize("case", ["Test1", "Test2", "Test3", "Test4"])
    def test_every_station_within_three_sigma(self, case):
        result = _survey(case)
        for station, (error, sigma) in _errors(result).items():
            assert abs(error) < 3.0 * sigma, (station, error, sigma)
        assert result.solution.statistics.global_test.passed

    def test_a_linear_drift_is_recovered_within_its_uncertainty(self):
        """0.01 mGal/h injected; the degree-1 coefficient is the drift per hour."""
        result = _survey("Test2")
        (session,) = result.drift
        (rate,) = result.drift[session].coefficients
        assert result.drift[session].treatment is DriftTreatment.JOINT
        assert rate.unit is Unit.ACCELERATION
        assert abs(rate.value - 0.01 * MGAL) < 2.0 * rate.std_dev

    def test_no_drift_is_found_where_none_was_put(self):
        (estimate,) = _survey("Test1").drift.values()
        (rate,) = estimate.coefficients
        assert abs(rate.value) < 2.0 * rate.std_dev

    def test_two_meters_with_different_calibrations_agree(self):
        """Test 4: calibrations 1.1 and 1.05 -- ten and five per cent. Without
        each meter's factor the two would disagree by milligal."""
        result = _survey("Test4")
        assert {r.instrument for r in result.sessions.values()} == {"B44", "B108"}
        assert max(abs(e) for e, _ in _errors(result).values()) < 0.005

    def test_an_uncalibrated_meter_is_visibly_wrong(self):
        """The same survey with the factors left at one: the check that the
        factor is doing something, not merely present."""
        library = ProfileLibrary()
        for meter in ("B44", "B108"):
            library.add_gravimeter(GravimeterProfile(id=meter))
        built = build_gravity_network(reduce_readings(_readings("Test4"), library), library)
        _held_at_truth(built)
        result = adjust_gravity_network(built)
        assert not result.solution.statistics.global_test.passed


class TestTheCalibrationUncertaintyReachesTheDifferences:
    """FR-204 and ``specs/12`` section 4.1: ``sigma_k * |dg|``, correlated."""

    def _built(self, sigma_k: float):
        library = ProfileLibrary()
        library.add_gravimeter(
            GravimeterProfile(
                id="B44", calibration_factor=Quantity.from_std_dev(1.0, sigma_k, Unit.DIMENSIONLESS)
            )
        )
        return build_gravity_network(reduce_readings(_readings("Test2"), library), library)

    def test_grows_with_the_size_of_the_difference(self):
        plain, scaled = self._built(0.0), self._built(1e-3)
        for oid, observation in scaled.network.observations.items():
            extra = observation.values[0].variance - plain.network.observations[oid].values[0].variance
            expected = (1e-3 * observation.values[0].value) ** 2
            assert extra == pytest.approx(expected, rel=1e-6, abs=1e-30)

    def test_is_one_correlated_cluster_per_instrument(self):
        built = self._built(1e-3)
        (cluster,) = built.network.clusters.values()
        matrix = cluster.covariance.matrix
        assert len(cluster.observation_ids) == len(built.network.observations)
        # Non-neighbouring differences share no occupation; only the scale term
        # correlates them.
        assert matrix[0, 5] != 0.0
        assert self._built(0.0).network.clusters[cluster.id].covariance.matrix[0, 5] == 0.0


class TestPreCorrectionAgainstJointEstimation:
    """Criterion 3.

    Two findings, and both are asserted. Pre-correction whose drift estimate
    is carried with its full covariance is not an approximation: it *is* the
    joint estimate, to machine precision, because the base readings' residuals
    carry no information about the station values. What makes pre-correction
    worse in practice is discarding that covariance -- treating the corrected
    differences as independent -- and that version agrees with joint
    estimation when the drift is linear and parts from it when it is not.
    """

    @pytest.mark.parametrize("case", ["Test2", "Test5"])
    def test_rigorous_pre_correction_is_the_joint_estimate(self, case):
        joint = _survey(case)
        pre = _survey(case, mode=DriftMode.PRE_CORRECTED)
        assert {r.treatment for r in pre.sessions.values()} == {DriftTreatment.PRE_CORRECTED}
        comparison = compare_treatments(joint, pre)
        assert max(abs(d.value) for d in comparison.differences.values()) < 1e-6 * UGAL

    def test_classical_pre_correction_agrees_where_the_drift_is_linear(self):
        comparison = compare_treatments(
            _survey("Test2"), _survey("Test2", mode=DriftMode.PRE_CORRECTED, correlated=False)
        )
        assert comparison.significant == ()
        assert max(abs(d.value) for d in comparison.differences.values()) < 1.0 * UGAL

    def test_and_differs_demonstrably_where_it_is_not(self):
        """Test 5's drift rises for two hours and falls back. The difference is
        reported station by station, against what the data's own precision
        allows, and every station exceeds it."""
        joint = _survey("Test5")
        classical = _survey("Test5", mode=DriftMode.PRE_CORRECTED, correlated=False)
        comparison = compare_treatments(joint, classical)
        assert set(comparison.significant) == {"sta2", "sta3", "sta4", "sta5"}
        assert abs(comparison.differences[comparison.largest].value) > 100.0 * UGAL

    def test_both_treatments_say_the_model_is_wrong(self):
        """Neither is right on Test 5, and neither pretends to be: the joint
        adjustment fails its global test, and the pre-correction's own fit to
        the base readings fails its chi-square and is labelled imposed."""
        joint = _survey("Test5")
        classical = _survey("Test5", mode=DriftMode.PRE_CORRECTED, correlated=False)
        assert not joint.solution.statistics.global_test.passed
        (estimate,) = classical.drift.values()
        assert estimate.verified is False
        assert Strategy.MODEL_ASSUMED in estimate.coefficients[0].strategies

    def test_a_linear_pre_correction_is_verified(self):
        (estimate,) = _survey("Test2", mode=DriftMode.PRE_CORRECTED).drift.values()
        assert estimate.base_station == "sta1"
        assert estimate.verified is True


class TestTheDatum:
    """Criteria 4 and 5."""

    def test_a_difference_only_network_has_a_defect_of_one(self):
        result = _survey("Test2", fixed=False)
        assert result.datum.defect == 1
        assert "inner constraint" in result.datum.removed_by

    def test_the_defect_is_still_reported_when_something_removes_it(self):
        absolute = AbsoluteGravity(
            "AG1", "sta1", Quantity.from_std_dev(50.0 * MGAL, 5 * UGAL, Unit.ACCELERATION)
        )
        result = _survey("Test2", fixed=False, absolutes=[absolute])
        assert result.datum.defect == 1
        assert result.datum.removed_by == "weighted absolute gravity at sta1"

    def test_absolute_values_are_weighted_not_fixed(self):
        """Two absolute values that disagree by 20 microgal more than the
        relative survey says: a fixed treatment would put the whole conflict
        into the relative differences; weighted, both absolutes move and both
        carry a residual."""
        values = [
            AbsoluteGravity("AG1", "sta1", Quantity.from_std_dev(50.0 * MGAL, 5 * UGAL, Unit.ACCELERATION)),
            AbsoluteGravity(
                "AG3", "sta3", Quantity.from_std_dev((45.0 + 0.020) * MGAL, 5 * UGAL, Unit.ACCELERATION)
            ),
        ]
        result = _survey("Test2", fixed=False, absolutes=values)
        residuals = {
            r.observation_id: r.residual
            for r in result.solution.observation_results
            if r.observation_id.startswith("absolute:")
        }
        assert set(residuals) == {"absolute:AG1", "absolute:AG3"}
        assert all(abs(v) > 1 * UGAL for v in residuals.values())
        assert result.gravity("sta1").std_dev > 0.0
        assert result.gravity("sta1").value != 50.0 * MGAL

    def test_a_fixed_station_is_held_exactly(self):
        result = _survey("Test2")
        assert result.run.layout.column("sta1", "g") is None
        assert result.datum.removed_by == "gravity held fixed at sta1"


class TestUncheckableObservationsAreNamed:
    """Criterion 6."""

    def test_a_pendant_station(self):
        """A station visited once, at the end of the loop, is determined by one
        difference and checked by nothing."""
        result = _survey("Test2", extra=[("sta7", 2549.0)])
        (pendant,) = [o.id for o in result.run.observations if "sta7" in o.stations]
        assert result.uncheckable == (pendant,)
        (redundancy,) = [
            r.redundancy for r in result.solution.observation_results if r.observation_id == pendant
        ]
        assert redundancy < 0.01

    def test_a_single_absolute_value(self):
        """The one absolute value that places the network: an error in it moves
        every station and nothing can see it."""
        absolute = AbsoluteGravity(
            "AG1", "sta1", Quantity.from_std_dev(50.0 * MGAL, 5 * UGAL, Unit.ACCELERATION)
        )
        result = _survey("Test2", fixed=False, absolutes=[absolute])
        assert "absolute:AG1" in result.uncheckable

    def test_a_redundant_loop_has_none(self):
        assert _survey("Test2").uncheckable == ()


class TestEveryOutputCarriesItsUncertainty:
    """Criteria 7 and 8."""

    def test_values_are_stored_in_si(self):
        """Readings arrive in mGal and are converted once, at the boundary; what
        the network holds and what the solution returns are m/s^2."""
        result = _survey("Test2")
        for observation in result.run.observations:
            assert observation.values[0].unit is Unit.ACCELERATION
            assert abs(observation.values[0].value) < 1e-3
        for station in result.solution.adjusted_stations:
            assert station.gravity.unit is Unit.ACCELERATION
            assert station.gravity.value == pytest.approx(TRUTH[station.station_id] * MGAL, abs=2e-7)

    def test_a_stored_solution_reads_back_in_si(self, tmp_path):
        """Store schema 3: the adjusted gravity survives a GeoPackage round trip,
        in m/s^2, bit for bit -- no display unit reaches storage."""
        from geocomp.core.models import Project
        from geocomp.io.store import open_store

        result = _survey("Test2")
        project = Project(id="gravity", name="gravity", default_crs="EPSG:4326")
        project.add_network(_survey_network("Test2"))
        with open_store(tmp_path / "gravity.gpkg", create=True) as store:
            store.write(project)
            store.write_solution(result.solution)
        with open_store(tmp_path / "gravity.gpkg") as store:
            (solution,) = store.read_solutions()
        back = {s.station_id: s.gravity for s in solution.adjusted_stations}
        for station in result.solution.adjusted_stations:
            assert back[station.station_id] == station.gravity

    def test_rigorous_inputs_give_a_rigorous_solution(self):
        result = _survey("Test2")
        assert result.solution.uncertainty_mode is UncertaintyMode.RIGOROUS
        assert all(s.gravity.variance > 0.0 for s in result.solution.adjusted_stations)
        assert all(c.variance > 0.0 for d in result.drift.values() for c in d.coefficients)

    def test_a_modelled_tide_makes_it_approximate(self):
        """Longman's uncertainty is a nominal figure, so a solution built on it
        says so (FR-203) -- the property no solution had before phase P8."""
        readings = [GravityReading(**{**r.__dict__, "tide_applied": False}) for r in _readings("Test2")]
        library = _library("Test2")
        built = build_gravity_network(reduce_readings(readings, library), library)
        _held_at_truth(built)
        result = adjust_gravity_network(built)
        assert result.solution.uncertainty_mode is UncertaintyMode.APPROXIMATE
        # Everything downstream of the tide is labelled, the drift included.
        for station in result.solution.adjusted_stations:
            assert Strategy.NOMINAL_PRECISION in station.gravity.strategies
        for estimate in result.drift.values():
            assert all(c.mode is UncertaintyMode.APPROXIMATE for c in estimate.coefficients)


def _survey_network(case: str):
    library = _library(case)
    built = build_gravity_network(reduce_readings(_readings(case), library), library)
    _held_at_truth(built)
    return built.network


class TestOccupationsAndSessions:
    def test_consecutive_readings_at_one_station_are_one_visit(self):
        readings = _readings("Test2")
        doubled = []
        for r in readings:
            doubled.append(r)
            doubled.append(
                GravityReading(
                    **{**r.__dict__, "id": r.id + "b", "instant": r.instant + timedelta(minutes=1)}
                )
            )
        library = _library("Test2")
        visits = group_occupations(reduce_readings(doubled, library))
        assert len(visits) == len(readings)
        assert all(len(v.readings) == 2 for v in visits)
        assert all(Strategy.INDEPENDENCE_ASSUMED in v.gravity.strategies for v in visits)
        # The mean of two equal-weight readings has sigma / sqrt(2).
        assert visits[0].gravity.std_dev == pytest.approx(SIGMA_MGAL * MGAL / math.sqrt(2))

    def test_a_session_that_visits_each_station_once_cannot_estimate_drift(self):
        assert not drift_is_estimable(["A", "B", "C"], [0.0, 1200.0, 2400.0], 1, 3600.0)
        assert drift_is_estimable(["A", "B", "A"], [0.0, 1200.0, 2400.0], 1, 3600.0)
        assert not drift_is_estimable(["A", "B", "A"], [0.0, 1200.0, 2400.0], 2, 3600.0)

    def test_joint_estimation_is_refused_where_it_is_impossible(self):
        from geocomp.core.errors import ValidationError

        readings = [r for r in _readings("Test2") if r.instant.hour < 13]
        library = _library("Test2")
        with pytest.raises(ValidationError) as caught:
            build_gravity_network(
                reduce_readings(readings, library), library, drift=DriftOptions(mode=DriftMode.JOINT)
            )
        assert caught.value.code == "validation.gravity_drift_not_estimable"

    def test_whatever_can_be_pre_corrected_can_be_estimated_jointly(self):
        """Why there is no automatic choice between the treatments: over every
        visiting order of three stations in up to six occupations, a base read
        often enough to fit the drift makes the joint estimate possible too."""
        from itertools import product

        for length in range(2, 7):
            for order in product("ABC", repeat=length):
                elapsed = [1200.0 * k for k in range(length)]
                for degree in (1, 2):
                    for base in set(order):
                        if order.count(base) >= degree + 1:
                            assert drift_is_estimable(list(order), elapsed, degree, 3600.0), (order, degree)

    def test_pre_correction_is_refused_without_enough_base_readings(self):
        from geocomp.core.errors import ValidationError

        library = _library("Test2")
        with pytest.raises(ValidationError) as caught:
            build_gravity_network(
                reduce_readings(_readings("Test2"), library),
                library,
                drift=DriftOptions(mode=DriftMode.PRE_CORRECTED, degree=3),
            )
        assert caught.value.code == "validation.gravity_drift_base_insufficient"


def test_the_truth_above_is_the_workbooks():
    """The transcription, checked wherever the workbook can be read."""
    openpyxl = pytest.importorskip("openpyxl", reason="openpyxl reads the vendored USGS workbook")
    workbook = openpyxl.load_workbook(DATA / "GSadjust_TestData.xlsx", data_only=True)
    sheets = {"Test1": "Test1", "Test2": "Test2", "Test3": "Test3", "Test4": "Test4", "Test5": "Test 5"}
    for case, sheet in sheets.items():
        rows = [row for row in workbook[sheet].iter_rows(values_only=True) if row[0] is not None]
        # The "True" data table comes first; the observation rows after it
        # start with a station too, and carry the operator in the next column.
        table: dict[str, float] = {}
        for row in rows:
            if isinstance(row[0], str) and row[0].startswith("sta") and isinstance(row[1], (int, float)):
                table.setdefault(row[0], row[1])
        for station, value in TRUTH.items():
            assert table[station] == value, (case, station)
        # The sheet's parameters sit a few columns in, as label-value pairs.
        stated = {
            label: value
            for row in workbook[sheet].iter_rows(values_only=True)
            for label, value in pairwise(row)
            if isinstance(label, str)
        }
        calibrations = [v for k, v in stated.items() if k.startswith("Calibration")]
        assert sorted(calibrations) == sorted(CASES[case]["calibration"].values()), case
        assert stated["Station standard deviation, mGal"] == SIGMA_MGAL
        if CASES[case]["drift_mgal_h"] is not None:
            assert stated["Drift rate, mGal/hr"] == CASES[case]["drift_mgal_h"], case


# -- phase P8b: what the algorithms need from the core ---------------------


class TestHoldingAStationByName:
    """The network algorithm's "known gravity" without a sigma: held exactly."""

    @staticmethod
    def _held(**extra):
        library = _library("Test2")
        return build_gravity_network(
            reduce_readings(_readings("Test2"), library),
            library,
            held={"sta1": Quantity.exact(TRUTH["sta1"] * MGAL, Unit.ACCELERATION)},
            **extra,
        )

    def test_it_is_the_same_as_the_constraint_written_by_hand(self):
        by_name = adjust_gravity_network(self._held())
        by_hand = _survey("Test2")
        for station in set(TRUTH) - {"sta1"}:
            assert by_name.gravity(station).value == pytest.approx(
                by_hand.gravity(station).value, abs=1e-15
            )
            assert by_name.gravity(station).std_dev == pytest.approx(
                by_hand.gravity(station).std_dev, rel=1e-12
            )
        assert by_name.datum.removed_by == "gravity held fixed at sta1"

    def test_the_held_station_keeps_its_location(self):
        """It is drawn on the map with the others; the layer needs somewhere to put it."""
        assert self._held().network.stations["sta1"].approx_position is not None

    def test_holding_a_station_nothing_observed_is_refused(self):
        from geocomp.core.errors import ValidationError

        library = _library("Test2")
        with pytest.raises(ValidationError) as caught:
            build_gravity_network(
                reduce_readings(_readings("Test2"), library),
                library,
                held={"sta9": Quantity.exact(0.0, Unit.ACCELERATION)},
            )
        assert caught.value.code == "validation.gravity_station_not_observed"

    def test_a_station_both_given_and_held_is_refused(self):
        from geocomp.core.errors import ValidationError

        with pytest.raises(ValidationError) as caught:
            self._held(stations={"sta1": Station(id="sta1")})
        assert caught.value.code == "validation.gravity_station_held_twice"


class TestDriftPreviews:
    """What pre-processing shows about each session before any adjustment."""

    def test_the_preview_is_the_base_fit_the_pre_correction_uses(self):
        from geocomp.core.techniques.gravimetry import drift_previews

        library = _library("Test2")
        (preview,) = drift_previews(reduce_readings(_readings("Test2"), library))
        assert preview.estimable
        assert (preview.base_station, preview.base_occupations) == ("sta1", 3)
        rate = preview.estimate.coefficients[0]
        assert abs(rate.value / MGAL - 0.01) <= 2.0 * rate.std_dev / MGAL
        (precorrected,) = _survey("Test2", mode=DriftMode.PRE_CORRECTED).drift.values()
        assert precorrected.coefficients[0].value == pytest.approx(rate.value, rel=1e-12)

    def test_a_session_that_visits_each_station_once_is_not_estimable(self):
        from geocomp.core.techniques.gravimetry import drift_previews

        library = _library("Test2")
        first_visits, seen = [], set()
        for reading in _readings("Test2"):
            if reading.station not in seen:
                seen.add(reading.station)
                first_visits.append(reading)
        (preview,) = drift_previews(reduce_readings(first_visits, library))
        assert not preview.estimable
        assert preview.estimate is None


class TestTheDocumentsBetweenTheAlgorithms:
    def test_a_reduced_reading_round_trips_through_json(self):
        """Pre-processing writes them, the network reads them back: nothing may
        change on the way, the tide and the height reduction included."""
        import dataclasses
        import json

        from geocomp.core.techniques.gravimetry import ReducedReading

        library = _library("Test2")
        raw = _readings("Test2")[:3]
        raw[1] = dataclasses.replace(
            raw[1],
            tide_applied=False,
            sensor_height=Quantity.from_std_dev(0.211, 0.002, Unit.METRE),
        )
        reduced = reduce_readings(raw, library)
        assert reduced[1].tide is not None and reduced[1].to_mark is not None
        for item in reduced:
            assert ReducedReading.from_dict(json.loads(json.dumps(item.to_dict()))) == item

    def test_every_difference_names_its_session(self):
        """The differences layer shows it, whichever way the drift was treated."""
        from geocomp.core.models import ObservationType

        library = _library("Test2")
        reduced = reduce_readings(_readings("Test2"), library)
        for mode in (DriftMode.JOINT, DriftMode.PRE_CORRECTED):
            built = build_gravity_network(reduced, library, drift=DriftOptions(mode=mode))
            sessions = {
                observation.meta.get("drift_owner") or observation.meta.get("session")
                for observation in built.network.observations.values()
                if observation.type is ObservationType.GRAVITY_DIFFERENCE
            }
            assert sessions == {"B44 2010/01/01"}, mode


class TestTheExportsCarryGravity:
    def test_the_adjusted_sheet_has_the_gravity_in_si(self):
        """Found in phase P8a and fixed in P8b: the CSV and XLSX exports wrote a
        station's position and nothing else, so a gravity solution's gravity was
        dropped on the way out."""
        from geocomp.io.tabular import sheet_rows

        result = _survey("Test2")
        headers, rows = sheet_rows("adjusted", None, result.solution)
        gravity, sigma = headers.index("gravity"), headers.index("gravity_std_dev")
        by_station = {row[0]: row for row in rows}
        for station in set(TRUTH) - {"sta1"}:
            assert by_station[station][gravity] == result.gravity(station).value
            assert by_station[station][sigma] == result.gravity(station).std_dev
