#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Regenerate the ETERNA tide series RD-07 judges Longman against.

``tests/data/rd07/eterna_hw95.json`` holds rigid-Earth tidal gravity computed
by ETERNA PREDICT 3.4 with the Hartmann-Wenzel (1995) catalogue, through
pygtide, at three latitudes and two epochs. ``tests/test_gravimetry_tides.py``
compares GeoComp's Longman implementation against it offline, and derives the
model's stated uncertainty from it (``specs/12`` section 4.2).

The series is GeoComp's own output of someone else's program, so it can be
committed; what must not be trusted is that it still *is* that program's
output. This script is the check::

    python3 scripts/check_tide_reference.py           # regenerate and compare
    python3 scripts/check_tide_reference.py --write   # regenerate and replace

It needs ``pygtide`` (MPL-2.0), which is a test-time reference and never a
runtime dependency of the plugin -- it is compiled Fortran, not shipped with
QGIS, and NFR-005 would need a decision to change that.

**Why rigid, not elastic.** With every amplitude factor set to 1, ETERNA and
Longman compute the same physical quantity and differ only in how well each
describes the Moon and the Sun; that isolates the formula's own error, which is
what the stated uncertainty is meant to be. The elastic factors are a separate
approximation, recorded as such in ``tides.py``.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE = REPO_ROOT / "tests" / "data" / "rd07" / "eterna_hw95.json"

#: The pygtide release the committed series came from. Pinned in
#: .github/workflows/reference.yml too.
PYGTIDE_VERSION = "0.9.1"

#: Three latitudes: the CG-5 survey's own site, Curitiba, and one at 60 N.
SITES = (
    {"name": "cg5_site", "latitude_deg": 9.7, "longitude_deg": 1.6, "height_m": 0.0},
    {"name": "curitiba", "latitude_deg": -25.45, "longitude_deg": -49.23, "height_m": 0.0},
    {"name": "north_60", "latitude_deg": 60.0, "longitude_deg": 10.0, "height_m": 0.0},
)
#: Two epochs thirteen years apart: Longman's mean elements are polynomials in
#: time from 1899, so their accuracy is worth checking at more than one date.
STARTS = ("2013-09-01", "2026-01-01")
DAYS = 30
SAMPLE_S = 3600
#: ETERNA's catalogue 7 is Hartmann and Wenzel (1995).
CATALOGUE = 7

#: Agreement required when regenerating: the series is written to 1e-3 nm/s^2,
#: so a larger difference is a different program, not a different rounding.
TOLERANCE_NM_S2 = 2e-3


def generate() -> dict:
    try:
        import numpy as np
        import pygtide
    except ImportError as error:  # pragma: no cover - exercised in CI only
        raise SystemExit(
            f"pygtide {PYGTIDE_VERSION} is needed: pip install pygtide=={PYGTIDE_VERSION} ({error})"
        ) from error

    from importlib.metadata import version

    installed = version("pygtide")
    series = []
    for site in SITES:
        for start in STARTS:
            predictor = pygtide.pygtide()
            # One wave group over every frequency, amplitude 1, phase 0: a rigid
            # Earth, which is what Longman computes before his factor.
            predictor.set_wavegroup(np.array([[0.0, 10.0, 1.0, 0.0]]))
            predictor.predict(
                site["latitude_deg"],
                site["longitude_deg"],
                site["height_m"],
                datetime.fromisoformat(start),
                24 * DAYS,
                SAMPLE_S,
                tidalpoten=CATALOGUE,
                tidalcompo=0,
                poltidecor=0,
                lodtidecor=0,
            )
            results = predictor.results()
            values = results["Signal [nm/s**2]"].to_numpy()
            first = results.iloc[0, 0].to_pydatetime()
            series.append(
                {
                    **site,
                    "start_utc": first.strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "interval_s": SAMPLE_S,
                    "gravity_nm_s2": [round(float(v), 3) for v in values],
                }
            )
    return {
        "description": (
            "Rigid-Earth tidal gravity (the change in observed gravity; positive means "
            "gravity increased) from ETERNA PREDICT with the Hartmann-Wenzel (1995) "
            "catalogue, pole and LOD tides off, one wave group with amplitude 1. "
            "Generated by scripts/check_tide_reference.py."
        ),
        "generator": {
            "pygtide": installed,
            "eterna": _text(getattr(pygtide.pygtide(), "fortran_version", "unknown")),
            "catalogue": "Hartmann and Wenzel (1995)",
            "tidalpoten": CATALOGUE,
            "wavegroup": [[0.0, 10.0, 1.0, 0.0]],
            "poltidecor": 0,
            "lodtidecor": 0,
        },
        "units": "nm/s^2",
        "series": series,
    }


def _text(value: object) -> str:
    """pygtide reports ETERNA's version as a Fortran character array."""
    import numpy as np

    if isinstance(value, np.ndarray):
        parts = np.atleast_1d(value).ravel().tolist()
        value = "".join(p.decode("ascii", "replace") if isinstance(p, bytes) else str(p) for p in parts)
    elif isinstance(value, bytes):
        value = value.decode("ascii", errors="replace")
    return " ".join(str(value).split())


def compare(fresh: dict, committed: dict) -> list[str]:
    problems: list[str] = []
    if len(fresh["series"]) != len(committed["series"]):
        return [f"{len(fresh['series'])} series regenerated, {len(committed['series'])} committed"]
    for new, old in zip(fresh["series"], committed["series"], strict=True):
        label = f"{old['name']} from {old['start_utc']}"
        if new["start_utc"] != old["start_utc"] or len(new["gravity_nm_s2"]) != len(old["gravity_nm_s2"]):
            problems.append(f"{label}: the time axis differs")
            continue
        worst = max(abs(a - b) for a, b in zip(new["gravity_nm_s2"], old["gravity_nm_s2"], strict=True))
        if worst > TOLERANCE_NM_S2:
            problems.append(f"{label}: differs by up to {worst:.4f} nm/s^2")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--write", action="store_true", help="replace the committed series")
    args = parser.parse_args(argv)

    fresh = generate()
    if args.write:
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(json.dumps(fresh, indent=1) + "\n", encoding="utf-8")
        print(f"wrote {FIXTURE.relative_to(REPO_ROOT)}: {len(fresh['series'])} series")
        return 0

    committed = json.loads(FIXTURE.read_text(encoding="utf-8"))
    problems = compare(fresh, committed)
    for problem in problems:
        print(f"FAIL: {problem}")
    if problems:
        return 1
    print(f"OK: {len(committed['series'])} series reproduced by pygtide {fresh['generator']['pygtide']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
