# SPDX-License-Identifier: GPL-2.0-or-later
"""The codes that still reach the user without a sentence: P12c-7's baseline.

NFR-006: an error message says what failed, why, and what the user can do. A
code with no template says none of that -- the user reads "GeoComp could not
complete the operation (data.some_code)" and nothing else. When P12c-7 first
counted, 457 of the codes GeoComp raises had no template; it wrote the 81 of
the engine package, where a failure is most often the user's input meeting
DynAdjust or RTKLIB, and froze the rest here. Its second pull request wrote the
28 of the file readers the algorithms use -- RINEX, field and levelling books
and their mappings, geoid grids, the tables export.

The list may only shrink. ``tests/structural/test_message_templates.py`` fails
on a code raised without a template that is not listed here -- a new code
arrives with its words -- and on a listed code that has gained a template or is
no longer raised, so an entry cannot outlive its reason. Some are guards no
user input reaches (a matrix of the wrong shape passed between two functions);
those still need words, because a defect is exactly when they surface.

Grouped by the directory that raises each code first.
"""

from __future__ import annotations

UNTEMPLATED: frozenset[str] = frozenset(
    {
        # core/ (49)
        "data.basemap_catalogue_unreadable",
        "data.covariance_duplicate_labels",
        "data.covariance_label_count",
        "data.covariance_not_positive_semidefinite",
        "data.covariance_not_square",
        "data.covariance_not_symmetric",
        "data.covariance_unit_count",
        "data.geoid_grid_not_finite",
        "data.geoid_grid_too_small",
        "validation.approximate_without_strategy",
        "validation.atan2_at_origin",
        "validation.basemap_duplicate_id",
        "validation.basemap_not_configured",
        "validation.basemap_url_carries_a_credential",
        "validation.basemap_url_without_tile_tokens",
        "validation.basemap_without_attribution",
        "validation.basemap_without_id",
        "validation.basemap_without_url",
        "validation.basemap_zoom_range",
        "validation.compound_unit_not_supported",
        "validation.correlated_scalar_path",
        "validation.coverage_not_ordered",
        "validation.display_angle_format_unknown",
        "validation.display_decimals_out_of_range",
        "validation.display_distance_unit_unknown",
        "validation.division_by_zero",
        "validation.geoid_outside_coverage",
        "validation.geoid_without_id",
        "validation.geoid_without_sigma",
        "validation.height_conversion_unsupported",
        "validation.height_wrong_unit",
        "validation.hypot_at_origin",
        "validation.incompatible_height_types",
        "validation.incompatible_units",
        "validation.jacobian_not_2d",
        "validation.jacobian_shape_mismatch",
        "validation.log_of_non_positive",
        "validation.negative_variance",
        "validation.not_a_quantity",
        "validation.output_label_count",
        "validation.output_unit_count",
        "validation.power_of_dimensioned_quantity",
        "validation.printed_half_width_not_positive",
        "validation.relative_uncertainty_of_zero",
        "validation.rigorous_with_strategies",
        "validation.sqrt_at_zero",
        "validation.sqrt_of_negative",
        "validation.unknown_covariance_label",
        "validation.value_count_mismatch",
        # core/adjustment/ (30)
        "computation.degenerate_sight",
        "computation.variance_component_negative",
        "computation.variance_component_unestimable",
        "computation.variance_components_not_converged",
        "computation.variance_components_singular",
        "data.weighted_constraint_components_missing",
        "data.weighted_constraint_singular",
        "validation.direction_without_setup",
        "validation.drift_degree_invalid",
        "validation.fixed_station_without_gravity",
        "validation.geocentric_frame_orthometric_constraint",
        "validation.geocentric_frame_partial_geodetic_constraint",
        "validation.geocentric_frame_projected_position",
        "validation.gnss_baseline_frame_mismatch",
        "validation.gravity_drift_scale_invalid",
        "validation.gravity_drift_times_missing",
        "validation.height_type_unsupported",
        "validation.known_value_for_unknown_station",
        "validation.negative_extent",
        "validation.not_a_difference_frame",
        "validation.observation_type_not_geocentric",
        "validation.undulation_without_position",
        "validation.unknown_defect_component",
        "validation.unknown_solver",
        "validation.variance_component_cluster_split",
        "validation.variance_component_group_unknown",
        "validation.weighting_coefficient_not_positive",
        "validation.weighting_gave_zero_sigma",
        "validation.weighting_unit_mismatch",
        "validation.weighting_unsupported_unit",
        # core/geodesy/ (13)
        "computation.cartesian_to_geodetic_degenerate",
        "computation.geodetic_angle_wrong_unit",
        "computation.geodetic_length_wrong_unit",
        "computation.inverse_projection_did_not_converge",
        "computation.point_scale_factor_undefined_at_the_pole",
        "computation.projection_outside_domain",
        "validation.ellipsoid_inverse_flattening_invalid",
        "validation.ellipsoid_semi_major_axis_not_positive",
        "validation.ellipsoid_unknown",
        "validation.frame_transformation_unavailable",
        "validation.frame_unknown",
        "validation.transformation_time_specific",
        "validation.utm_zone_out_of_range",
        # core/instruments/ (39)
        "validation.calibration_table_factor_not_positive",
        "validation.calibration_table_inconsistent",
        "validation.calibration_table_not_increasing",
        "validation.calibration_table_too_short",
        "validation.counter_gravimeter_without_table",
        "validation.counter_reading_unit",
        "validation.cyclic_error_without_wavelength",
        "validation.default_sigma_negative",
        "validation.duplicate_gravimeter_profile",
        "validation.duplicate_instrument_profile",
        "validation.duplicate_level_profile",
        "validation.duplicate_levelling_class",
        "validation.duplicate_reflector_profile",
        "validation.edm_specification_negative",
        "validation.gravimeter_calibration_factor_invalid",
        "validation.gravimeter_profile_without_id",
        "validation.gravimeter_reading_unit",
        "validation.gravimeter_sigma_negative",
        "validation.gravity_gravimeter_with_table",
        "validation.instrument_sigma_negative",
        "validation.level_profile_without_id",
        "validation.level_sigma_negative",
        "validation.level_stadia_factor_not_positive",
        "validation.level_without_reading_sigma",
        "validation.levelling_class_negative_limit",
        "validation.levelling_class_without_id",
        "validation.missing_stochastic_model",
        "validation.negative_line_length",
        "validation.negative_setup_count",
        "validation.no_instrument_profile",
        "validation.no_level_profile",
        "validation.non_positive_set_count",
        "validation.profile_wrong_unit",
        "validation.stated_sigma_negative",
        "validation.unknown_instrument_profile",
        "validation.unknown_level_profile",
        "validation.unknown_levelling_class",
        "validation.unknown_observation_kind",
        "validation.unknown_reflector_profile",
        # core/models/ (45)
        "data.active_observation_with_rejection",
        "data.antenna_height_unit",
        "data.baseline_frame_unknown",
        "data.cluster_duplicate_members",
        "data.cluster_size_mismatch",
        "data.cluster_without_members",
        "data.constrained_station_without_position",
        "data.duplicate_campaign",
        "data.duplicate_cluster",
        "data.duplicate_gnss_session",
        "data.duplicate_network",
        "data.duplicate_observation",
        "data.duplicate_station",
        "data.gnss_session_ends_before_it_starts",
        "data.gnss_session_without_id",
        "data.observation_arity",
        "data.observation_component_count",
        "data.observation_requires_cluster",
        "data.observation_setup_height_unit",
        "data.observation_type_ignores_setup_heights",
        "data.observation_value_not_a_quantity",
        "data.observation_value_unit",
        "data.station_without_id",
        "validation.adjusted_gravity_unit",
        "validation.constraint_unknown_components",
        "validation.constraint_without_components",
        "validation.constraint_without_position",
        "validation.epoch_instant_naive",
        "validation.epoch_not_finite",
        "validation.epoch_required",
        "validation.free_constraint_with_detail",
        "validation.gravity_constraint_unit",
        "validation.gravity_constraint_without_value",
        "validation.gravity_value_without_gravity_component",
        "validation.observation_is_not_scalar",
        "validation.position_component_count",
        "validation.position_component_not_a_quantity",
        "validation.position_component_unit",
        "validation.position_without_crs",
        "validation.schema_version_too_new",
        "validation.solution_without_crs",
        "validation.station_not_in_solution",
        "validation.unknown_position_component",
        "validation.weighted_constraint_without_covariance",
        "validation.weighted_gravity_constraint_without_uncertainty",
        # core/preanalysis/ (6)
        "geocomp.duplicate_station",
        "geocomp.no_default_sigma",
        "geocomp.observation_without_stations",
        "geocomp.station_without_id",
        "geocomp.unknown_observation",
        "geocomp.unknown_station",
        # core/statistics/ (7)
        "validation.confidence_out_of_range",
        "validation.degrees_of_freedom_out_of_range",
        "validation.ellipse_wrong_dimension",
        "validation.incomplete_beta_domain",
        "validation.incomplete_gamma_domain",
        "validation.probability_out_of_range",
        "validation.relative_ellipse_dimension_mismatch",
        # core/techniques/gnss/ (32)
        "data.antenna_offset_unit",
        "data.baseline_between_one_station",
        "data.baseline_cluster_empty",
        "data.baseline_cluster_mixed_frames",
        "data.baseline_component_count",
        "data.baseline_component_unit",
        "data.baseline_covariance_size",
        "data.comparison_mixed_frames",
        "data.comparison_mixed_station_pairs",
        "data.comparison_needs_two_configurations",
        "data.comparison_reference_not_found",
        "data.duplicate_reference_station",
        "data.gnss_loop_leg_not_ecef",
        "data.gnss_loop_mixed_antenna_reduction",
        "data.reference_station_database_missing",
        "data.reference_station_database_unreadable",
        "data.reference_station_not_found",
        "data.reference_station_position_count",
        "data.reference_station_position_unit",
        "data.reference_station_without_frame",
        "data.reference_station_without_id",
        "data.trajectory_covariance_not_local",
        "data.trajectory_point_frame",
        "validation.antenna_height_already_reduced",
        "validation.antenna_height_is_slant",
        "validation.antenna_reduction_needs_ecef",
        "validation.baseline_already_local",
        "validation.gnss_loop_leg_missing",
        "validation.gnss_loop_repeats_a_station",
        "validation.gnss_loop_too_short",
        "validation.reference_station_frame_mismatch",
        "validation.reference_station_without_velocity",
        # core/techniques/gravimetry/ (14)
        "validation.absolute_gravity_invalid",
        "validation.drift_occupation_mismatch",
        "validation.drift_time_scale_invalid",
        "validation.gravity_base_station_not_in_session",
        "validation.gravity_network_without_readings",
        "validation.gravity_reading_incomplete",
        "validation.gravity_reading_instant_naive",
        "validation.gravity_reading_sensor_height_unit",
        "validation.gravity_station_held_twice",
        "validation.gravity_station_not_in_solution",
        "validation.gravity_vertical_gradient_invalid",
        "validation.tide_amplification_invalid",
        "validation.tide_instant_naive",
        "validation.tide_latitude_out_of_range",
        # core/techniques/integration/ (4)
        "validation.combination_gravity_without_its_network",
        "validation.combination_routed_to_dynadjust",
        "validation.combination_station_without_position",
        "validation.engine_unknown",
        # core/techniques/levelling/ (37)
        "validation.benchmark_height_wrong_unit",
        "validation.benchmark_not_in_network",
        "validation.benchmark_without_height_type",
        "validation.benchmark_without_position",
        "validation.geoid_model_named_without_grid",
        "validation.height_difference_wrong_unit",
        "validation.known_difference_wrong_unit",
        "validation.latitude_out_of_range",
        "validation.level_setup_repeats_a_station",
        "validation.level_setup_without_foresight",
        "validation.level_setup_without_id",
        "validation.levelling_line_discontinuous",
        "validation.levelling_line_without_id",
        "validation.levelling_line_without_setups",
        "validation.levelling_network_without_lines",
        "validation.levelling_network_without_setups",
        "validation.line_extent_not_positive",
        "validation.line_length_unknown",
        "validation.loop_discontinuous",
        "validation.loop_does_not_close",
        "validation.loop_without_lines",
        "validation.negative_sight_distance",
        "validation.orthometric_correction_wrong_unit",
        "validation.reciprocal_pair_same_station",
        "validation.reciprocal_pairs_disagree",
        "validation.reciprocal_second_pair_reversed",
        "validation.section_runs_disagree",
        "validation.staff_reading_not_a_quantity",
        "validation.staff_reading_without_station",
        "validation.staff_reading_wrong_unit",
        "validation.station_not_foresighted",
        "validation.three_wire_out_of_order",
        "validation.three_wire_reading_not_a_quantity",
        "validation.three_wire_wrong_unit",
        "validation.unknown_weighting_mode",
        "validation.variance_inflation_below_one",
        "validation.weighted_benchmark_without_uncertainty",
        # core/techniques/total_station/ (30)
        "computation.intersection_did_not_converge",
        "computation.intersection_indeterminate",
        "computation.intersection_on_a_station",
        "computation.resection_did_not_converge",
        "computation.resection_indeterminate",
        "computation.resection_on_a_known_point",
        "validation.atmosphere_wrong_unit",
        "validation.connected_traverse_without_closing_point",
        "validation.correlation_out_of_range",
        "validation.face_pair_different_targets",
        "validation.face_pair_wrong_faces",
        "validation.height_below_earth_centre",
        "validation.humidity_out_of_range",
        "validation.intersection_needs_two_stations",
        "validation.leg_angle_wrong_unit",
        "validation.leg_distance_wrong_unit",
        "validation.non_positive_set_number",
        "validation.non_positive_wavelength",
        "validation.reading_without_target",
        "validation.reading_wrong_unit",
        "validation.reduction_wrong_unit",
        "validation.resection_direction_to_unknown_point",
        "validation.resection_needs_three_points",
        "validation.scale_factor_wrong_unit",
        "validation.setup_without_station",
        "validation.sight_wrong_unit",
        "validation.temperature_not_absolute",
        "validation.temperature_wrong_unit",
        "validation.traverse_without_legs",
        "validation.unsupported_observation_dimension",
        # core/visualization/ (6)
        "validation.ellipse_too_few_vertices",
        "validation.exaggeration_not_finite",
        "validation.exaggeration_not_positive",
        "validation.extent_not_positive",
        "validation.scale_reference_not_positive",
        "validation.target_fraction_out_of_range",
        # io/ (31) -- all in krumm.py and adjust.py, which read the RD-11 and ADJUST
        # reference corpora for the tests and scripts; no algorithm reaches them.
        "data.adjust_angle_out_of_range",
        "data.adjust_azimuths_unsupported",
        "data.adjust_cannot_express_observation",
        "data.adjust_control_without_covariance",
        "data.adjust_control_without_sigmas",
        "data.adjust_declared_counts_disagree",
        "data.adjust_fewer_stations_than_declared",
        "data.adjust_file_half_valued",
        "data.adjust_file_too_short",
        "data.adjust_header_not_five_counts",
        "data.adjust_header_not_integers",
        "data.adjust_not_a_number",
        "data.adjust_observation_row_unrecognised",
        "data.adjust_observation_station_unknown",
        "data.adjust_station_row_too_short",
        "data.krumm_angle_unreadable",
        "data.krumm_baseline_antenna_heights",
        "data.krumm_coordinate_row_too_short",
        "data.krumm_datum_token_unreadable",
        "data.krumm_datum_unknown",
        "data.krumm_dynamic_datum_unsupported",
        "data.krumm_free_datum_partial",
        "data.krumm_handler_unimplemented",
        "data.krumm_levelling_length_not_positive",
        "data.krumm_mixed_dimensionality",
        "data.krumm_observation_station_unknown",
        "data.krumm_row_too_short",
        "data.krumm_section_unknown",
        "data.krumm_section_unsupported",
        "data.krumm_setup_heights_incomplete",
        "data.krumm_value_not_a_number",
        # reports/ (3)
        "validation.template_name_not_bare",
        "validation.template_not_found",
        "validation.template_unknown_token",
        # services/ (2)
        "validation.no_project_open",
        "validation.setting_scope_not_allowed",
    }
)
